trigger:
- main

pool:
  name: Devops_Agent

steps:
- checkout: self
- task: Maven@4
  inputs:
    mavenPomFile: 'demo/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkDirectory: 'C:\Program Files\Java\jdk-25.0.2'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean install'